Festival-backend/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('api/v1/festivals', array('as' => 'api.festivals', 'uses' => 'Api\Controllers\FestivalController@get_index'));
Route::get('api/v1/lineups', array('as' => 'api.lineups', 'uses' => 'Api\Controllers\LineupController@get_index'));
Route::get('api/v1/colors', array('as' => 'api.colors', 'uses' => 'Api\Controllers\ColorController@get_index'));

Route::group(array('prefix' => 'admin'), function()
{
    Route::group(array('before' => 'auth'), function()
    {
    Route::any('/',                'App\Controllers\Admin\FestivalsController@index');


        Route::put('lineups/addstage/{id}', array('as' => 'admin.lineups.addstage', 'uses' => 'App\Controllers\Admin\LineupController@addstage'));
        Route::put('lineups/updatestage/{id}', array('as' => 'admin.lineups.updatestage', 'uses' => 'App\Controllers\Admin\LineupController@updatestage'));

    Route::resource('lineups',    'App\Controllers\Admin\LineupController');
    Route::resource('festivals',       'App\Controllers\Admin\FestivalsController');
        Route::resource('users',       'App\Controllers\Admin\UsersController');
        Route::resource('stages',       'App\Controllers\Admin\StagesController');
        Route::resource('colors',       'App\Controllers\Admin\ColorsController');

    });

    Route::get('logout', 'App\Controllers\Admin\AuthController@getLogout');
    Route::get('login', 'App\Controllers\Admin\AuthController@getLogin');
    Route::post('login',  'App\Controllers\Admin\AuthController@postLogin');
    Route::get('/logout', [
        'as'   => 'admin.logout',
        function () {
            Auth::logout();

            return Redirect::to('/admin/login');
        }
    ])->before('auth');

});

Festival-backend/app/views/admin/_partials/assets.blade.php
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<link href="{{ URL::asset('assets/css/bootstrap.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/css/datepicker.css') }}" rel="stylesheet">
<link href="{{ URL::asset('assets/css/bootstrap-timepicker.min.css') }}" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
<link href="{{ URL::asset('assets/css/main.css') }}" rel="stylesheet">

<script src="//code.jquery.com/jquery-1.9.1.min.js"></script>

<script src="{{ URL::asset('assets/js/bootstrap.js') }}"></script>
<script src="{{ URL::asset('assets/js/bootstrap-datepicker.js') }}"></script>
<script src="{{ URL::asset('assets/js/bootstrap-timepicker.min.js') }}"></script>

<script src="{{ URL::asset('assets/js/script.js') }}"></script>

Festival-backend/app/views/admin/_partials/header.blade.php
    <div class="navbar-inner">
        <div class="container">





            @if (Auth::check())
            <p id="username"><span class="glyphicon glyphicon-user"></span> {{Auth::user()->username}}</p>


            @endif

            @include('admin._partials.navigation')
        </div>
    </div>

Festival-backend/app/views/admin/_partials/navigation.blade.php
@if (Auth::user())

<div class="col-sm-6 nav">
    <ul class="nav">
        <div class="col-xs-6 navigation">
        <li class="{{ Request::is('admin/festivals*') ? 'active' : null }}"><a href="{{ URL::route('admin.festivals.index') }}"><i class="icon-headphones"></i> Festivals</a></li>
            </div>
            <div class="col-xs-6 navigation">
        <li class="{{ Request::is('admin/lineups*') ? 'active' : null }}"><a href="{{ URL::route('admin.lineups.index') }}"><i class="icon-star"></i> Lineups</a></li>
            </div>
        <div class="col-xs-6 navigation">
        <li class="{{ Request::is('admin/stages*') ? 'active' : null }}"><a href="{{ URL::route('admin.stages.index') }}"><i class="glyphicon glyphicon-tower"></i> Stages</a></li>
        </div>
        <div class="col-xs-6 navigation">
        <li class="{{ Request::is('admin/users*') ? 'active' : null }}"><a href="{{ URL::route('admin.users.index') }}"><i class="icon-user"></i> Users</a></li>
        </div>
        <div class="col-xs-6 navigation">
            <li class="{{ Request::is('admin/colors*') ? 'active' : null }}"><a href="{{ URL::route('admin.colors.index') }}"><i class="glyphicon glyphicon-tint"></i> Colors</a></li>
        </div>
        <div class="col-xs-6 navigation">
        <li><a href="{{ URL::route('admin.logout') }}"><i class="glyphicon glyphicon-log-out"></i> Logout</a></li>
        </div>


        @endif
    </ul>
</div>